### ISSUE TITLE
OutOfMemoryException | Unable to create new native threads error

### ISSUE THREAD

**Issue by ankit2711** [datacleaner/extension_elasticsearch#20]
Using the latest extension randomly gives java.lang.OutOfMemoryError: unable to create new native thread. 
This happens when the ES indexing job extension based jobs is executed multiple times in DC. 
This does not happen with the version 2.6 where the ElasticSearchDatastores are not used but instead a local ElasticSearchClientFactory is used. 

Stacktrace :-
66) Error injecting constructor, java.lang.OutOfMemoryError: unable to create new native thread
  at org.elasticsearch.threadpool.ThreadPool.<init>(Unknown Source)
  while locating org.elasticsearch.threadpool.ThreadPool
  for parameter 3 at org.elasticsearch.client.transport.TransportClientNodesService.<init>(Unknown Source)
  while locating org.elasticsearch.client.transport.TransportClientNodesService
Caused by: java.lang.OutOfMemoryError: unable to create new native thread
        at java.lang.Thread.start0(Native Method)
        at java.lang.Thread.start(Thread.java:714)
        at org.elasticsearch.threadpool.ThreadPool.<init>(ThreadPool.java:159)
        at sun.reflect.GeneratedConstructorAccessor411.newInstance(Unknown Source)
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:422)
        at org.elasticsearch.common.inject.DefaultConstructionProxyFactory$1.newInstance(DefaultConstructionProxyFactory.java:54)
        at org.elasticsearch.common.inject.ConstructorInjector.construct(ConstructorInjector.java:86)
        at org.elasticsearch.common.inject.ConstructorBindingImpl$Factory.get(ConstructorBindingImpl.java:98)
        at org.elasticsearch.common.inject.ProviderToInternalFactoryAdapter$1.call(ProviderToInternalFactoryAdapter.java:45)
        at org.elasticsearch.common.inject.InjectorImpl.callInContext(InjectorImpl.java:837)
        at org.elasticsearch.common.inject.ProviderToInternalFactoryAdapter.get(ProviderToInternalFactoryAdapter.java:42)
        at org.elasticsearch.common.inject.Scopes$1$1.get(Scopes.java:57)
        at org.elasticsearch.common.inject.InternalFactoryToProviderAdapter.get(InternalFactoryToProviderAdapter.java:45)
        at org.elasticsearch.common.inject.SingleParameterInjector.inject(SingleParameterInjector.java:42)
        at org.elasticsearch.common.inject.SingleParameterInjector.getAll(SingleParameterInjector.java:66)
        at org.elasticsearch.common.inject.ConstructorInjector.construct(ConstructorInjector.java:85)
        at org.elasticsearch.common.inject.ConstructorBindingImpl$Factory.get(ConstructorBindingImpl.java:98)
        at org.elasticsearch.common.inject.ProviderToInternalFactoryAdapter$1.call(ProviderToInternalFactoryAdapter.java:45)
        at org.elasticsearch.common.inject.InjectorImpl.callInContext(InjectorImpl.java:837)
        at org.elasticsearch.common.inject.ProviderToInternalFactoryAdapter.get(ProviderToInternalFactoryAdapter.java:42)
        at org.elasticsearch.common.inject.Scopes$1$1.get(Scopes.java:57)
        at org.elasticsearch.common.inject.InternalFactoryToProviderAdapter.get(InternalFactoryToProviderAdapter.java:45)
        at org.elasticsearch.common.inject.InjectorBuilder$1.call(InjectorBuilder.java:200)
        at org.elasticsearch.common.inject.InjectorBuilder$1.call(InjectorBuilder.java:193)
        at org.elasticsearch.common.inject.InjectorImpl.callInContext(InjectorImpl.java:830)
        at org.elasticsearch.common.inject.InjectorBuilder.loadEagerSingletons(InjectorBuilder.java:193)
        at org.elasticsearch.common.inject.InjectorBuilder.injectDynamically(InjectorBuilder.java:175)
        at org.elasticsearch.common.inject.InjectorBuilder.build(InjectorBuilder.java:110)
        at org.elasticsearch.common.inject.Guice.createInjector(Guice.java:93)
        at org.elasticsearch.common.inject.Guice.createInjector(Guice.java:70)
        at org.elasticsearch.common.inject.ModulesBuilder.createInjector(ModulesBuilder.java:59)
        at org.elasticsearch.client.transport.TransportClient.<init>(TransportClient.java:187)
        at org.elasticsearch.client.transport.TransportClient.<init>(TransportClient.java:123)
        at org.datacleaner.connection.ElasticSearchDatastore.createDatastoreConnection(ElasticSearchDatastore.java:127)
        at org.datacleaner.connection.UsageAwareDatastore.getDatastoreConnection(UsageAwareDatastore.java:117)
        at org.datacleaner.connection.UsageAwareDatastore.openConnection(UsageAwareDatastore.java:128)
        at org.datacleaner.connection.ElasticSearchDatastore.openConnection(ElasticSearchDatastore.java:151)
        at org.datacleaner.extension.elasticsearch.ElasticSearchIndexAnalyzer.init(ElasticSearchIndexAnalyzer.java:89)
        at sun.reflect.GeneratedMethodAccessor174.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:497)
        at org.datacleaner.descriptors.AbstractMethodDescriptor.invoke(AbstractMethodDescriptor.java:79)
        at org.datacleaner.descriptors.InitializeMethodDescriptorImpl.initialize(InitializeMethodDescriptorImpl.java:44)
        at org.datacleaner.lifecycle.LifeCycleHelper.initialize(LifeCycleHelper.java:180)
        at org.datacleaner.job.tasks.InitializeTask.executeInternal(InitializeTask.java:83)
        at org.datacleaner.job.tasks.InitializeTask.execute(InitializeTask.java:55)
        at org.datacleaner.job.concurrent.TaskRunnable.run(TaskRunnable.java:61)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)

**Comment by kaspersorensen** [comment]
I think the issue here is some kind of combination issue with other usages of ElasticSearch. What I see is that every open connection to ElasticSearch is taking up a significant thread pool. If we have much concurrent use of ElasticSearch then we could get into this condition.

I know that on the system where this happened, another product was also creating ElasticSearch connections. This probably increases the risk of failure.

A suggestion from my side would be to try and limit the number of concurrent connections to ElasticSearch. A way we might do this is to not open the connection as part of ```ElasticSearchIndexFlushAction``` (which runs for each chunk of records in the buffer) but instead do it only once in an ```@Initialize``` method of ```ElasticSearchIndexAnalyzer``` and then pass that connection into the flush action instead of the datastore. If we try that - also remember to close the connection then in a ```@Close``` method on ```ElasticSearchIndexAnalyzer```.
